---
title: "ETC1010 Groups, Semester one, 2020"
output: html_document
---

# Find your username below, and your group, then find your group members!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r get-groups, include = FALSE}
library(googlesheets4)
googlesheets4::sheets_auth(email = "nicholas.tierney@monash.edu")

library(dplyr)
groups <- read_sheet("https://docs.google.com/spreadsheets/d/1YZAhzZvrPyIPHsTl0MGsLiNzL4U1s2-AbdO0SdFufyk/edit#gid=0",
                     .name_repair = janitor::make_clean_names) %>% 
  filter(enrolled == "Enrolled") %>% 
  select(username,
         group)
```

```{r print-dt, echo = FALSE}
DT::datatable(groups)
```

```{r create-zoom-groups}

zoom_col_names <- c("Pre-assign Room Name",
                    "Email Address")

zoom_rooms <- groups %>% 
  group_by(group) %>% 
  tidyr::nest() %>%
  ungroup() %>% 
  mutate(room = rep(x = 1:9,
                    length.out = 37)) %>% 
  tidyr::unnest(cols = c(data)) %>% 
  select(room, email_address) %>% 
  mutate(room = paste0("room ", room)) %>% 
  setNames(zoom_col_names)
  
write_csv(zoom_rooms, 
```

